const IMAGE_PATHS = {
    backgrounds: {
      green_wood: {
        wood7: './assets/img/game_backgrounds/4/7.png',
        wood6: './assets/img/game_backgrounds/4/6.png',
        wood4: './assets/img/game_backgrounds/4/4.png',
        wood2: './assets/img/game_backgrounds/4/2.png',
        wood1: './assets/img/game_backgrounds/4/1.png',
      },
      blue_wood: {
        wood3: './assets/img/game_backgrounds/3/3.png',
        wood2: './assets/img/game_backgrounds/3/2.png',
      },
    },
    game_items: {
      candle: './assets/img/game_items/magic effects/candle.png',
      skull: './assets/img/skull/skull 000.png',
      crystal: './assets/img/game_items/magic effects/crystal.png',
      key: './assets/img/game_items/magic effects/key.png',
      hearts: [
        './assets/img/game_ui/heart_empty.png',
        './assets/img/game_ui/heart_full.png',
      ],
      poison: [
        './assets/img/poison/1.png',
        './assets/img/poison/2.png',
        './assets/img/poison/3.png',
        './assets/img/poison/4.png',
        './assets/img/poison/5.png',
        './assets/img/poison/6.png',
        './assets/img/poison/7.png',
        './assets/img/poison/8.png',
      ],
      trap: [
        './assets/img/obstacles/trap/trap1.png',
        './assets/img/obstacles/trap/trap2.png',
        './assets/img/obstacles/trap/trap3.png',
        './assets/img/obstacles/trap/trap4.png',
        './assets/img/obstacles/trap/trap5.png',
        './assets/img/obstacles/trap/trap6.png',
      ],
      door: [
        './assets/img/door/door_0.png',
        './assets/img/door/door_1.png',
        './assets/img/door/door_2.png',
        './assets/img/door/door_3.png',
        './assets/img/door/door_4.png',
      ],
    },
    natural_objects: {
      cloud: './assets/img/clouds/2.png',
    },
    character: {
      idle: [
        './assets/img/wizard/idle/idle_000.png',
        './assets/img/wizard/idle/idle_001.png',
        './assets/img/wizard/idle/idle_002.png',
        './assets/img/wizard/idle/idle_003.png',
        './assets/img/wizard/idle/idle_004.png',
        './assets/img/wizard/idle/idle_005.png',
        './assets/img/wizard/idle/idle_006.png',
        './assets/img/wizard/idle/idle_007.png',
        './assets/img/wizard/idle/idle_008.png',
        './assets/img/wizard/idle/idle_009.png',
      ],
      walk: [
        './assets/img/wizard/walk/walk_000.png',
        './assets/img/wizard/walk/walk_001.png',
        './assets/img/wizard/walk/walk_002.png',
        './assets/img/wizard/walk/walk_003.png',
        './assets/img/wizard/walk/walk_004.png',
        './assets/img/wizard/walk/walk_005.png',
        './assets/img/wizard/walk/walk_006.png',
        './assets/img/wizard/walk/walk_007.png',
        './assets/img/wizard/walk/walk_008.png',
        './assets/img/wizard/walk/walk_009.png',
      ],
      jump: [
        './assets/img/wizard/jump/jump_000.png',
        './assets/img/wizard/jump/jump_001.png',
        './assets/img/wizard/jump/jump_002.png',
        './assets/img/wizard/jump/jump_003.png',
        './assets/img/wizard/jump/jump_004.png',
        './assets/img/wizard/jump/jump_005.png',
        './assets/img/wizard/jump/jump_006.png',
        './assets/img/wizard/jump/jump_007.png',
        './assets/img/wizard/jump/jump_008.png',
        './assets/img/wizard/jump/jump_009.png',
      ],
      attack: [
        './assets/img/wizard/attack/attack_000.png',
        './assets/img/wizard/attack/attack_001.png',
        './assets/img/wizard/attack/attack_002.png',
        './assets/img/wizard/attack/attack_003.png',
        './assets/img/wizard/attack/attack_004.png',
        './assets/img/wizard/attack/attack_005.png',
        './assets/img/wizard/attack/attack_006.png',
      ],
      die: [
        './assets/img/wizard/die/die_000.png',
        './assets/img/wizard/die/die_001.png',
        './assets/img/wizard/die/die_002.png',
        './assets/img/wizard/die/die_003.png',
        './assets/img/wizard/die/die_004.png',
        './assets/img/wizard/die/die_005.png',
        './assets/img/wizard/die/die_006.png',
        './assets/img/wizard/die/die_007.png',
        './assets/img/wizard/die/die_008.png',
        './assets/img/wizard/die/die_009.png',
      ],
      hurt: [
        './assets/img/wizard/hurt/hurt_000.png',
        './assets/img/wizard/hurt/hurt_001.png',
        './assets/img/wizard/hurt/hurt_002.png',
        './assets/img/wizard/hurt/hurt_003.png',
        './assets/img/wizard/hurt/hurt_004.png',
        './assets/img/wizard/hurt/hurt_005.png',
        './assets/img/wizard/hurt/hurt_006.png',
        './assets/img/wizard/hurt/hurt_007.png',
        './assets/img/wizard/hurt/hurt_008.png',
        './assets/img/wizard/hurt/hurt_009.png',
      ],
    },
    troll: {
      walk: [
        './assets/img/troll/walk/walk_000.png',
        './assets/img/troll/walk/walk_001.png',
        './assets/img/troll/walk/walk_002.png',
        './assets/img/troll/walk/walk_003.png',
        './assets/img/troll/walk/walk_004.png',
        './assets/img/troll/walk/walk_005.png',
        './assets/img/troll/walk/walk_006.png',
        './assets/img/troll/walk/walk_007.png',
        './assets/img/troll/walk/walk_008.png',
        './assets/img/troll/walk/walk_009.png',
      ],
      attack: [
        './assets/img/troll/attack/attack_000.png',
        './assets/img/troll/attack/attack_001.png',
        './assets/img/troll/attack/attack_002.png',
        './assets/img/troll/attack/attack_003.png',
        './assets/img/troll/attack/attack_004.png',
        './assets/img/troll/attack/attack_005.png',
        './assets/img/troll/attack/attack_006.png',
        './assets/img/troll/attack/attack_007.png',
        './assets/img/troll/attack/attack_008.png',
        './assets/img/troll/attack/attack_009.png',
      ],
      hurt: [
        './assets/img/troll/hurt/hurt_000.png',
        './assets/img/troll/hurt/hurt_001.png',
        './assets/img/troll/hurt/hurt_002.png',
        './assets/img/troll/hurt/hurt_003.png',
        './assets/img/troll/hurt/hurt_004.png',
        './assets/img/troll/hurt/hurt_005.png',
        './assets/img/troll/hurt/hurt_006.png',
        './assets/img/troll/hurt/hurt_007.png',
        './assets/img/troll/hurt/hurt_008.png',
        './assets/img/troll/hurt/hurt_009.png',
      ],
      dead: [
        './assets/img/troll/die/die_000.png',
        './assets/img/troll/die/die_001.png',
        './assets/img/troll/die/die_002.png',
        './assets/img/troll/die/die_003.png',
        './assets/img/troll/die/die_004.png',
        './assets/img/troll/die/die_005.png',
        './assets/img/troll/die/die_006.png',
        './assets/img/troll/die/die_007.png',
        './assets/img/troll/die/die_008.png',
        './assets/img/troll/die/die_009.png',
      ],
    },
    knight: {
      walk: [
        './assets/img/knight/walk/walk0.png',
        './assets/img/knight/walk/walk1.png',
        './assets/img/knight/walk/walk2.png',
        './assets/img/knight/walk/walk3.png',
        './assets/img/knight/walk/walk4.png',
        './assets/img/knight/walk/walk5.png',
      ],
      attack: [
        './assets/img/knight/attack/attack0.png',
        './assets/img/knight/attack/attack1.png',
        './assets/img/knight/attack/attack2.png',
        './assets/img/knight/attack/attack3.png',
        './assets/img/knight/attack/attack4.png',
        './assets/img/knight/attack/attack5.png',
        './assets/img/knight/attack/attack6.png',
      ],
      hurt: [
        './assets/img/knight/hurt/hurt0.png',
        './assets/img/knight/hurt/hurt1.png',
      ],
      dead: [
        './assets/img/knight/death/death0.png',
        './assets/img/knight/death/death1.png',
        './assets/img/knight/death/death2.png',
        './assets/img/knight/death/death3.png',
        './assets/img/knight/death/death4.png',
        './assets/img/knight/death/death5.png',
      ],
    },
    snake: {
      walk: [
        './assets/img/snake/walk/walk0.png',
        './assets/img/snake/walk/walk1.png',
        './assets/img/snake/walk/walk2.png',
        './assets/img/snake/walk/walk3.png',
      ],
      attack: [
        './assets/img/snake/attack/attack0.png',
        './assets/img/snake/attack/attack1.png',
        './assets/img/snake/attack/attack2.png',
        './assets/img/snake/attack/attack3.png',
      ],
      hurt: [
        './assets/img/snake/hurt/hurt0.png',
        './assets/img/snake/hurt/hurt1.png',
      ],
      dead: [
        './assets/img/snake/die/die0.png',
        './assets/img/snake/die/die1.png',
        './assets/img/snake/die/die2.png',
        './assets/img/snake/die/die3.png',
      ],
    },
    gameUI: {
      status_bars: {
        health: [
          './assets/img/game_ui/statusbars/statusbar-health/0.png',
          './assets/img/game_ui/statusbars/statusbar-health/20.png',
          './assets/img/game_ui/statusbars/statusbar-health/40.png',
          './assets/img/game_ui/statusbars/statusbar-health/60.png',
          './assets/img/game_ui/statusbars/statusbar-health/80.png',
          './assets/img/game_ui/statusbars/statusbar-health/100.png',
        ],
        poison: [
          './assets/img/game_ui/statusbars/statusbar-poison/0.png',
          './assets/img/game_ui/statusbars/statusbar-poison/20.png',
          './assets/img/game_ui/statusbars/statusbar-poison/40.png',
          './assets/img/game_ui/statusbars/statusbar-poison/60.png',
          './assets/img/game_ui/statusbars/statusbar-poison/80.png',
          './assets/img/game_ui/statusbars/statusbar-poison/100.png',
        ],
        endboss: [
          './assets/img/game_ui/statusbars/statusbar-endboss/0.png',
          './assets/img/game_ui/statusbars/statusbar-endboss/20.png',
          './assets/img/game_ui/statusbars/statusbar-endboss/40.png',
          './assets/img/game_ui/statusbars/statusbar-endboss/60.png',
          './assets/img/game_ui/statusbars/statusbar-endboss/80.png',
          './assets/img/game_ui/statusbars/statusbar-endboss/100.png',
        ],
      },
      audio_icons: {
        sound_on: './assets/img/app_icons/soundon.png',
        sound_off: './assets/img/app_icons/sound_off_orange.png',
      },
      quit_game: './assets/img/game_ui/quit.png',
      try_again: './assets/img/game_ui/try_again.png',
      game_over: './assets/img/game_ui/login&pass/game_over.png',
    },
  };